# Site Info
title: '김용주의 블로그'
tagline: '김용주님의 블로그'
description: '맨땅에 헤딩하는 블로그입니다'
baseurl: ""
url: https://odsn.github.io

# Site configurations
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: YONGJOO KIM
  description: 김용주
  contact:
    github:    https://github.com/odsn
    email:    21500121@handong.edu

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { 실전프로젝트: '/blog/categories/#실전프로젝트'}
    - { Database: '/blog/categories/#Database' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus


# Use the following plug-ins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed